--- 
title_meta  : Chapter 0
title       : Sandbox
description : "In this chapter, you will learn the basics of how to work on DataCamp and how to handle with exercises. 
Since many of you are working with iPads, there will also be some advice regarding special characters such as `^` or `'`. Let's get started!"
 
--- type:NormalExercise lang:r xp:0 skills:1 key:exercise0_1
## THE WARM UP STARTS HERE: How does DataCamp work
 
In the box below you can see the instructions for the exercise. 
On the right in the upper window you can type your code. That window is called editor. 
You can execute the code by pressing Ctrl+Enter (Cmd+Enter in Mac) when the cursor is on the same line with your command,
and when you are done with the exercises, you can press the Submit-button.
If your command is on multiple lines you must select all those rows and then Ctrl+Enter or Cmd+Enter.
When you run your commands, the results appear in the window under the editor. That window is called console.

Tips for iPad users:
In case you are using an iPad, you can just go ahead and run all the commands by pressing the Submit-button. 
If you do this when you are not yet 
finished and some sort of error message appears, you can try to comment out the parts that you have not completed yet. 
That can be done by inserting a hashtag `#` at the beginning of the not completed lines.
